### ISSUE TITLE
Should "~ryptography" be "cryptography" ?

### ISSUE THREAD

**Issue by PhillRogers** [rebkwok/kpcli#10]
Installing (Windows) gets an error which might imply a typo in the code somewhere:
"ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Python311\\Lib\\site-packages\\~ryptography\\hazmat\\bindings\\_rust.pyd'
Consider using the `--user` option or check the permissions."

Should "~ryptography" be "cryptography" ?

**Comment by compilercomplied** [comment]
Hi Phil,

Just found a runtime problem in my windows box, but I was able to install it.

This is the kpcli that I could install:
```shell
pip3 install kpcli
. . .
Installing collected packages: kpcli
Successfully installed kpcli-0.4.1
```

And these are my pip/python versions:
```shell
pip --version
pip 23.1.2 from C:\Users\____\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip (python 3.9)

python3 --version
Python 3.9.13
```

Cryptography seems to be correctly defined on the pyproject.toml
https://github.com/rebkwok/kpcli/blob/1c64e7274345d28ebc2607e22211a4ee9f6dbe7f/pyproject.toml#L19 And git history seems to have the correct package all the time.

**Comment by PhillRogers** [comment]
Yea, thanks for looking. I got a clean install by uninstalling the package & then installing another package which depends on it.
