### ISSUE TITLE
Performance opening/decrypting database

### ISSUE THREAD

**Issue by iridos** [rebkwok/kpcli#17]
Hi,
I just had a look as keepassxc ( https://github.com/keepassxreboot/keepassxc/ )and kpcli seems better for my usecase in pretty much every regard except one. 

With keepassxc I created a test database therein with more encryption iterations (193548380) that takes ~8 seconds opening time with keepassxc. Opening the same file with kpcli takes 110 seconds. 

More iterations should be useful to some degree against bruteforcing and would be generally desireable, but not feasible to a useful degree with kpcli if it takes ~ factor 10 longer than other implementations. 

This is probably an issue with the underlying cryptography.fernet module which is a pure-python implementation(?). 

Maybe switching to https://pypi.org/project/pycryptodome/ could be an option? No idea how difficult such a switch would be though. 

Best,
I.

**Comment by rebkwok** [comment]
Closing as this project is no longer actively maintained. The project it is based on, KeePassX, has been deprecated since 2021. Please consider switching to [KeePassXC](https://keepassxc.org/) which is based on KeePassX and is compatible with the same .kdbx file format. KeePassXC ships with a command line utility which does more or less everything you'd want this package for (and some more).

**Comment by iridos** [comment]
Hm, ok, a that is a huge pity. 

Actually I had seen and tried keepassxc-cli and it doesn't come anywhere close to what I  need. Typical workflow consists of a opening database with db-password, a search + one or multiple entry-show, close database. keepassxc does not have an internal interface and makes me re-eneter the long password for every single operation, which makes it not feasible to use for me. 

Up to now, kpcli is still in the Debian archives. 

Cheers.

**Comment by rebkwok** [comment]
Feel free to fork this repo or take over maintenance if you would like.

If it helps, I find the keepassxc command line invocation annoyingly wordy, so a I have a function in .bashrc/.zshrc that aliases it and means I don't have to pass the database location every time. You could make it also populate the password (at your own risk etc etc as you'll need to have it in an env variable/config file somewhere) like:

```
function kp(){
  db_name="$1"
  shift 1
  echo "$KP_PASSWORD" | /path/to/KeePassXC-*.AppImage cli "$db_name" /path/to/keepass/db "$@"
}
```
On the command line now, I just type `kp clip -b <item name>`; the kp function takes care of the db location and password
