### ISSUE TITLE
Nice idea, but needs real CLI support

### ISSUE THREAD

**Issue by otheus** [rebkwok/kpcli#26]
Nice idea here. With a few minor modifications, you could make it into an actual CLI tool:
* support accepting the XML sub-tree as a file (or stdin) for new or replacing entries
* support command line options (including the password) for new or modifying entries (and option to suppress warnings about danger or accepting password on the command line)
* or allow the entry-specific password to be specified by an environment variable or by stdin

Example:

```
kpcli add [--name ][ENTRY-NAME] [--group Group1[:Group2[:Group3...]] ] [--user Username] [--password <Password-Spec> ] [--notes Notes] 

where <Password-Spec> is one of:

   e:VARNAME     -- use the environment variable VARNAME
   s:STRING         -- use the unencrypted STRING
   f:stdin               -- read from standard input
   f:FILENAME      -- read from filename

```

This allows usage such as:

```
kpcli add --name Entry1 --group MyGroup:AutoGenerated  --password f:<( openssl rand -base64 14 )

or 

openssl rand -base64 14 | \
kpcli add --name Entry1 --group MyGroup:AutoGenerated  --password f:stdin

export MYPASS
read -s MYPASS
(terminal input secret)
kpcli add --name Entry1 --group MyGroup:AutoGenerated  --password e:MYPASS

or

kpcli add --name Entry1 --group MyGroup:AutoGenerated  --password s:$MYPASS
WARNING: Passing passwords as arguments is known to be insecure; password may be sniffed by other users on the system or may show up in logs or your shell's history!

kpcli add --ignore-warnings --name Entry1 --group MyGroup:AutoGenerated  --password s:$MYPASS

```

**Comment by rebkwok** [comment]
Closing as this project is no longer actively maintained. The project it is based on, KeePassX, has been deprecated since 2021. Please consider switching to [KeePassXC](https://keepassxc.org/) which is based on KeePassX and is compatible with the same .kdbx file format. KeePassXC ships with a command line utility which does more or less everything you'd want this package for (and some more).
