### ISSUE TITLE
What's the relation of this project with https://sourceforge.net/projects/kpcli/ ?

### ISSUE THREAD

**Issue by strk** [rebkwok/kpcli#3]
The https://sourceforge.net/projects/kpcli/ version seems to be beyond 3.1 while this one is at 2.something (according to ChangeLog) so I'm wondering what's the relation between this and that. The sourceforge one is indicated as the source of the `kpcli` Ubuntu 20.10 package.

**Comment by pmorch** [comment]
It looks like this one is implemented in Python and the other one in perl. My guess is that there is no relation except that they have the same name.
